version: "3"

services:
  cars:
    image: test-dm/cars:${TAG:-latest}
    build:
      context: ./services/cars
      dockerfile: Dockerfile
    environment:
      - CARS_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - '3001:3001'
    depends_on:
      - mysql 
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
